[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_BASE_URL = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 